# -*- coding: utf-8 -*-
"""
Created on Tue Dec 20 18:41:58 2022

@author: Russell J Adams

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fib(n):
    fibs = [1,1]
    while fibs[-1] < n:
        fibs.append(fibs[-1]+fibs[-2])
    return fibs

fibs = fib(4000000)
print(sum([i for i in fibs if i % 2 == 0]))